name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Run Jest tests
        run: yarn test

      - name: Upload coverage report
        if: always() # Ensures this step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/