name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Run Jest tests
        run: yarn test

      - name: Display coverage report
        if: success() # Only run if tests pass
        run: |
          echo "Coverage summary:"
          cat coverage/lcov-report/index.html